# Generated by Django 3.1 on 2020-09-11 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер категории')),
                ('category_name', models.CharField(max_length=100, verbose_name='Категория')),
                ('category_show', models.BooleanField(default=True, verbose_name='Видимость')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер заказа')),
                ('order_branch', models.CharField(max_length=100, verbose_name='Филиал')),
                ('order_client', models.CharField(max_length=100, verbose_name='Клиент')),
                ('order_courier', models.CharField(max_length=100, verbose_name='Курьер')),
                ('order_items', models.JSONField(verbose_name='Товары')),
                ('order_comment', models.TextField(verbose_name='Комментарий')),
                ('order_date_time', models.DateTimeField(verbose_name='Время')),
                ('order_payment', models.CharField(max_length=100, verbose_name='Оплата')),
                ('order_status', models.CharField(max_length=100, verbose_name='Статус')),
                ('order_delivery_address', models.CharField(max_length=100, verbose_name='Адрес доставки')),
                ('order_history', models.JSONField(verbose_name='История')),
                ('order_price', models.IntegerField(verbose_name='Сумма')),
                ('order_sale', models.JSONField(verbose_name='Скидка')),
                ('order_marks', models.JSONField(verbose_name='Отметки')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер товара')),
                ('item_index', models.IntegerField(unique=True, verbose_name='Артикул')),
                ('item_price', models.IntegerField(verbose_name='Цена')),
                ('item_color', models.CharField(max_length=100, verbose_name='Цвет')),
                ('item_description', models.TextField(verbose_name='Описание')),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_order.categories')),
            ],
        ),
    ]
