# Generated by Django 3.1 on 2020-11-01 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(blank=True, max_length=100, verbose_name='Название филиала')),
                ('branch_address', models.CharField(blank=True, max_length=100, verbose_name='Адрес филиала')),
                ('branch_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер категории')),
                ('category_name', models.CharField(max_length=100, verbose_name='Категория')),
                ('category_show', models.BooleanField(default=True, verbose_name='Видимость')),
                ('category_sort', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['category_sort'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер товара')),
                ('item_index', models.IntegerField(blank=True, null=True, verbose_name='Артикул')),
                ('item_name', models.CharField(default='', max_length=100, verbose_name='Наименование')),
                ('item_price', models.IntegerField(verbose_name='Цена')),
                ('item_description', models.TextField(blank=True, verbose_name='Описание')),
                ('item_show', models.BooleanField(default=True, verbose_name='Видимость')),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_order.category', verbose_name='Категория')),
                ('item_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='new_order.color', verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='LearningFrom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_from_name', models.CharField(blank=True, max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Узнали из',
                'verbose_name_plural': 'Узнали из',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_name', models.CharField(blank=True, max_length=100, verbose_name='Название')),
                ('payment_sort', models.IntegerField(default=0, help_text='99 - выбирается по умолчанию', verbose_name='Сортировка')),
                ('payment_api', models.CharField(blank=True, max_length=10, null=True, verbose_name='API')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Варианты оплаты',
                'ordering': ['payment_sort'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale', models.CharField(max_length=10, verbose_name='Скидка')),
                ('sale_order', models.IntegerField(default=0, verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
                'ordering': ['sale_order', 'sale'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item_order_number', models.IntegerField(verbose_name='Номер заказа')),
                ('order_item_price', models.CharField(max_length=10, verbose_name='Цена')),
                ('order_item_quantity', models.CharField(blank=True, max_length=10, verbose_name='Кол-во')),
                ('order_item_summa', models.CharField(max_length=10, verbose_name='Сумма')),
                ('order_item_item_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='new_order.item', verbose_name='Товары в заказе')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_client_phone', models.CharField(blank=True, max_length=15, verbose_name='Телефон Клиента')),
                ('order_client_name', models.CharField(blank=True, max_length=100, verbose_name='Имя Клиента')),
                ('order_delivery_street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Улица')),
                ('order_delivery_house', models.CharField(blank=True, max_length=10, null=True, verbose_name='Дом')),
                ('order_delivery_entrance', models.CharField(blank=True, max_length=10, null=True, verbose_name='Подъезд')),
                ('order_delivery_floor', models.CharField(blank=True, max_length=10, null=True, verbose_name='Этаж')),
                ('order_delivery_flat', models.CharField(blank=True, max_length=10, null=True, verbose_name='Квартира')),
                ('order_comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('order_date_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время заказа')),
                ('order_certificate', models.CharField(blank=True, max_length=100, verbose_name='Сертификат')),
                ('order_payment', models.CharField(blank=True, max_length=100, verbose_name='Оплата')),
                ('order_marks', models.CharField(blank=True, max_length=100, verbose_name='Отметки')),
                ('order_person', models.CharField(default=1, max_length=10, verbose_name='Приборы')),
                ('order_sale_count', models.CharField(blank=True, max_length=10, verbose_name='Скидка в рублях')),
                ('order_price', models.CharField(blank=True, max_length=10, verbose_name='Сумма')),
                ('order_number', models.IntegerField(verbose_name='Номер заказа')),
                ('order_status', models.CharField(blank=True, max_length=100, verbose_name='Статус')),
                ('order_courier', models.CharField(blank=True, max_length=100, verbose_name='Курьер')),
                ('order_history', models.JSONField(blank=True, null=True, verbose_name='История')),
                ('order_deleted', models.BooleanField(default=False, verbose_name='Заказ удален')),
                ('order_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='new_order.branch', verbose_name='Филиал')),
                ('order_learning_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='new_order.learningfrom', verbose_name='Узнали из')),
                ('order_sale', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='new_order.sale', verbose_name='Скидка')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
