# Generated by Django 3.1 on 2020-09-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_name',
            field=models.CharField(default='', max_length=100, verbose_name='Наименование'),
        ),
    ]
