# Generated by Django 3.1 on 2020-10-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_order', '0002_auto_20201022_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['order', 'sale'], 'verbose_name': 'Скидка', 'verbose_name_plural': 'Скидки'},
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_order',
            field=models.IntegerField(default=0, verbose_name='Сортировка'),
        ),
    ]
