# Generated by Django 3.1 on 2020-10-22 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_order', '0003_auto_20201022_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='id',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_item_order_number',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, primary_key='order_number', serialize=False, to='new_order.order', verbose_name='Номер заказа'),
        ),
    ]
