# Generated by Django 3.1 on 2020-09-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_order', '0004_auto_20200911_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Номер категории'),
        ),
    ]
