# Generated by Django 3.1 on 2020-10-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_order', '0005_auto_20201022_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_deleted',
            field=models.BooleanField(default=False, verbose_name='Заказ удален'),
        ),
    ]
