# Generated by Django 3.1 on 2020-10-22 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_order', '0006_order_order_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['sale_order', 'sale'], 'verbose_name': 'Скидка', 'verbose_name_plural': 'Скидки'},
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_sort',
            field=models.IntegerField(default=0, verbose_name='Сортировка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_person',
            field=models.CharField(default=1, max_length=10, verbose_name='Приборы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_sale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='new_order.sale', verbose_name='Скидка'),
        ),
    ]
