# Generated by Django 3.1 on 2020-09-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_order', '0009_auto_20200911_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_index',
            field=models.IntegerField(blank=True, verbose_name='Артикул'),
        ),
    ]
