# Generated by Django 3.1 on 2020-09-11 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_order', '0010_auto_20200911_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='new_order.color'),
        ),
    ]
