# Generated by Django 3.1 on 2020-09-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_order', '0012_auto_20200911_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_show',
            field=models.BooleanField(default=True, verbose_name='Видимость'),
        ),
    ]
