# Generated by Django 3.1 on 2020-09-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_order', '0014_auto_20200913_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_delivery_address',
            field=models.JSONField(max_length=100, verbose_name='Адрес доставки'),
        ),
    ]
