# Generated by Django 3.1 on 2020-09-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_order', '0015_auto_20200913_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_branch',
            field=models.CharField(blank=True, max_length=100, verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_courier',
            field=models.CharField(blank=True, max_length=100, verbose_name='Курьер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_delivery_address',
            field=models.JSONField(blank=True, max_length=100, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_history',
            field=models.JSONField(blank=True, verbose_name='История'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_price',
            field=models.IntegerField(default=0, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, max_length=100, verbose_name='Статус'),
        ),
    ]
