# Generated by Django 3.1 on 2020-09-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_order', '0017_auto_20200913_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_delivery_address',
            field=models.JSONField(blank=True, max_length=100, null=True, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_history',
            field=models.JSONField(blank=True, null=True, verbose_name='История'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_items',
            field=models.JSONField(blank=True, null=True, verbose_name='Товары'),
        ),
    ]
