# Generated by Django 3.1 on 2020-09-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_order', '0018_auto_20200913_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_delivery_address',
        ),
        migrations.AddField(
            model_name='order',
            name='order_delivery_entrance',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Подъезд'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_delivery_flat',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_delivery_floor',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_delivery_house',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_delivery_street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Улица'),
        ),
    ]
