# Generated by Django 3.1 on 2020-09-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_order', '0019_auto_20200914_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100, verbose_name='Название филиала')),
                ('branch_address', models.CharField(max_length=100, verbose_name='Адрес филиала')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_marks',
            field=models.JSONField(blank=True, verbose_name='Отметки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(blank=True, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_payment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Оплата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_person',
            field=models.IntegerField(blank=True, verbose_name='Приборы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_price',
            field=models.IntegerField(blank=True, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_sale',
            field=models.IntegerField(blank=True, verbose_name='Скидка'),
        ),
    ]
