# Generated by Django 3.1 on 2020-09-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_order', '0020_auto_20200914_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Адрес филиала'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название филиала'),
        ),
    ]
