# Generated by Django 3.1 on 2020-09-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_order', '0023_auto_20200914_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningFrom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_from_name', models.CharField(blank=True, max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Узнали из',
                'verbose_name_plural': 'Узнали из',
            },
        ),
    ]
