# Generated by Django 3.1 on 2020-09-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_order', '0025_auto_20200914_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_name', models.CharField(blank=True, max_length=100, verbose_name='Название')),
                ('payment_api', models.CharField(blank=True, max_length=10, verbose_name='API')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Варианты оплаты',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='order_learning_from',
            field=models.CharField(blank=True, max_length=100, verbose_name='Узнали из'),
        ),
    ]
