# Generated by Django 3.1 on 2020-09-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_order', '0027_auto_20200915_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_marks',
            field=models.CharField(choices=[(2, 'Доставка'), (3, 'С собой'), (4, 'В зале'), (1, 'x')], default=1, max_length=100, verbose_name='Отметки'),
        ),
    ]
