# Generated by Django 3.1 on 2020-09-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_order', '0029_auto_20200915_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_items',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_branch',
            field=models.CharField(choices=[(1, '')], default=0, max_length=100, verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_learning_from',
            field=models.CharField(choices=[(1, '---'), (2, 'Сайт rolltime16.ru'), (3, 'Агрегаторы yandex или delivery')], default=1, max_length=100, verbose_name='Узнали из'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_payment',
            field=models.CharField(choices=[(1, '---'), (2, 'Нал.'), (3, 'Б / нал.'), (4, 'Агрегатор')], default=1, max_length=100, verbose_name='Оплата'),
        ),
    ]
