# Generated by Django 3.1 on 2020-09-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_order', '0030_auto_20200915_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale', models.CharField(max_length=10, verbose_name='Скидка')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
                'ordering': ['sale'],
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='order_branch',
            field=models.CharField(choices=[(1, 'Сахарова, 31')], default=0, max_length=100, verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_person',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15)], default=1, verbose_name='Приборы'),
        ),
    ]
