# Generated by Django 3.1 on 2020-09-16 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_order', '0031_auto_20200915_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_sale_count',
            field=models.IntegerField(choices=[(6, '-10%'), (10, '-100%'), (7, '-20%'), (3, '-3%'), (8, '-30%'), (4, '-5%'), (9, '-50%'), (5, '-7%'), (1, 'Без скидки'), (2, 'Суммой')], default=1, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_sale',
            field=models.CharField(choices=[(6, '-10%'), (10, '-100%'), (7, '-20%'), (3, '-3%'), (8, '-30%'), (4, '-5%'), (9, '-50%'), (5, '-7%'), (1, 'Без скидки'), (2, 'Суммой')], default=1, max_length=10, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_item_item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_order.item', verbose_name='Товары в заказе'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_item_order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_order.order', verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_item_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_item_quantity',
            field=models.CharField(choices=[(99, 'Удалить'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1, max_length=10, verbose_name='Кол-во'),
        ),
    ]
