# Generated by Django 3.1 on 2020-09-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_order', '0032_auto_20200916_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_person',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15')], default=1, verbose_name='Приборы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_sale',
            field=models.CharField(blank=True, choices=[(6, '-10%'), (10, '-100%'), (7, '-20%'), (3, '-3%'), (8, '-30%'), (4, '-5%'), (9, '-50%'), (5, '-7%'), (1, 'Без скидки'), (2, 'Суммой')], default=1, max_length=10, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_item_quantity',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (99, 'Удалить')], default=1, max_length=10, verbose_name='Кол-во'),
        ),
    ]
