# Generated by Django 3.1 on 2020-09-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_order', '0033_auto_20200917_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_sale_count',
            field=models.IntegerField(blank=True, verbose_name='Скидка'),
        ),
    ]
