# Generated by Django 3.1 on 2020-09-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_order', '0038_auto_20200917_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_marks',
            field=models.CharField(choices=[(2, 'Доставка'), (3, 'С собой'), (4, 'В зале'), (1, 'x')], max_length=100, verbose_name='Отметки'),
        ),
    ]
