# Generated by Django 3.1 on 2020-09-17 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_order', '0043_auto_20200917_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_branch',
            field=models.CharField(choices=[(1, 'Сахарова, 31')], max_length=100, verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_marks',
            field=models.CharField(blank=True, choices=[(2, 'Доставка'), (3, 'С собой'), (4, 'В зале'), (1, 'x')], max_length=100, verbose_name='Отметки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_sale',
            field=models.CharField(blank=True, choices=[(6, '-10%'), (10, '-100%'), (7, '-20%'), (3, '-3%'), (8, '-30%'), (4, '-5%'), (9, '-50%'), (5, '-7%'), (1, 'Без скидки'), (2, 'Суммой')], max_length=10, verbose_name='Скидка'),
        ),
    ]
