# Generated by Django 3.1 on 2020-09-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_order', '0044_auto_20200917_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_branch',
            field=models.CharField(blank=True, choices=[(1, 'Сахарова, 31')], max_length=100, verbose_name='Филиал'),
        ),
    ]
