# Generated by Django 3.1 on 2020-09-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_order', '0047_auto_20200917_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_price',
            field=models.CharField(blank=True, max_length=10, verbose_name='Сумма'),
        ),
    ]
