# Generated by Django 3.1 on 2020-09-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_order', '0049_auto_20200917_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_sale_count',
            field=models.CharField(blank=True, max_length=10, verbose_name='Скидка в рублях'),
        ),
    ]
