# Generated by Django 3.1 on 2020-09-17 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_order', '0050_auto_20200917_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_branch',
            field=models.CharField(blank=True, max_length=100, verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_learning_from',
            field=models.CharField(blank=True, max_length=100, verbose_name='Узнали из'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_marks',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отметки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_payment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Оплата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_person',
            field=models.CharField(blank=True, max_length=10, verbose_name='Приборы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_sale',
            field=models.CharField(blank=True, max_length=10, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_item_order_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='new_order.order', verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_item_price',
            field=models.CharField(max_length=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_item_quantity',
            field=models.CharField(blank=True, max_length=10, verbose_name='Кол-во'),
        ),
    ]
