# Generated by Django 3.1 on 2020-09-17 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_order', '0052_auto_20200917_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='new_order.branch', verbose_name='Филиал'),
        ),
    ]
