# Generated by Django 3.1 on 2020-09-17 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_order', '0054_auto_20200917_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_learning_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='new_order.learningfrom', verbose_name='Узнали из'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='new_order.payment', verbose_name='Оплата'),
        ),
    ]
